### PR TITLE
use improved high numerical precision linspace from Base

### LINKED ISSUE #39: bug in kde_range
There seem to be a problem with `kde_range` in univariant.jl: The range that is returned sometimes  has the wrong number of points.

Can be easily detected by inserting `length(lo:step:hi) == npoints || @show "ERROR", length(lo:step:hi)`
before returning. 

I think it results from a problem is [`linspace`](https://github.com/JuliaLang/julia/issues/14420).

Suggested fix:

 return `lo + (0:npoints-1)*step` instead of `lo:step:hi`

### PR DESCRIPTION
**Pull request by tlnagy**
KernelDensity.jl rolled its own range generator which suffers from similar flaws as Base's linspace prior to being fixed in JuliaLang/julia#18777. This closes #39. @andreasnoack @simonbyrne. This needed for https://github.com/GiovineItalia/Gadfly.jl/pull/1157

Master 
```julia
julia> length(KernelDensity.kde_range((0.12698109160784082, 0.9785547869337731), 256))
255
```

This PR
```julia
julia> length(KernelDensity.kde_range((0.12698109160784082, 0.9785547869337731), 256))
256
```

### CODE REVIEW

**Comment by tlnagy** [comment]
Tests are passing on 0.6 and the failures on the nightlies appears unrelated.

File: src/univariate.jl [hunk 1]
```diff
@@ -66,8 +66,7 @@ function kde_range(boundary::Tuple{Real,Real}, npoints::Int)
     lo, hi = boundary
     lo < hi || error("boundary (a,b) must have a < b")
 
-    step = (hi - lo) / (npoints-1)
-    lo:step:hi
+    linspace(lo, hi, npoints)
```
Comment (ararslan) [inline src/univariate.jl]: `linspace` is deprecated in 0.7, so this should be `Compat.range(lo, stop=hi, length=npoints)`

Comment (tlnagy) [reply src/univariate.jl]: Good catch.
